### ISSUE TITLE
Add support for `string-set!` and `string-fill!`

### ISSUE THREAD

**Issue by acieroid** [softwarelanguageslab/maf#14]
This would require store-allocating strings, and may have an impact on the size of the store, as well as on precision.

This is required for benchmarks such as `gambit/compiler.scm`, `gambit/scheme.scm`, and `gambit/slatex.scm`

**Comment by noahvanes** [comment]
Strings are now store-allocated, and primitives `string-set!` and `string-fill!` have been added.

Caveat: the current `string-set!` implementation is sound, but not always the most precise (cf. #17) 

Notes about the mentioned benchmark programs:
- benchmark `gambit/compiler.scm` won't work in the concrete interpreter yet, due to lacking support of `call/cc` (see #18)
- benchmark `gambit/scheme.scm` seems to be broken for other reasons
- benchmark `gambit/slatex.scm` requires further IO configuration to run properly
